### ISSUE TITLE
Use HTTPS on Netlify

### ISSUE THREAD

**Issue by nickserv** [nickserv/nickserv.github.io#75]
- [ ] Deploy to Netlify
- [ ] Review https://nickmccurdy.netlify.com/
- [ ] Use Netlify nameservers to migrate custom domain
- [ ] Wait for DNS propagation
- [ ] Enable certificate and force HTTPS
- [ ] Update URLs
- [ ] Rename repository
- [ ] Fix 404 page
- [ ] Fix mixed content warnings

**Comment by nickmccurdy** [comment]
Moved to #76

**Comment by nickserv** [comment]
Using #89 for GitHub Pages instead.
